name: Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Infra
        uses: actions/checkout@v4

      - name: Checkout VPC module
        uses: actions/checkout@v4
        with:
          repository: ayuuushhiiii/VPC_Module
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: VPC_Module

      - name: Checkout Subnet module
        uses: actions/checkout@v4
        with:
          repository: ayuuushhiiii/subnet_module
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: subnet_module

      - name: Checkout EC2 module
        uses: actions/checkout@v4
        with:
          repository: ayuuushhiiii/EC2
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: EC2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1   # change if youâ€™re using another region

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan
